from divicast.base.symbol import ValuedMultiton


class Daemon(ValuedMultiton):
    """
    神煞
    """

    Tianyiguiren = (0, "天乙贵人")
    Tiandeguiren = (1, "天德贵人")
    Yuedeguiren = (2, "月德贵人")
    Tiandehe = (3, "天德合")
    Yuedehe = (4, "月德合")
    Tianshexing = (5, "天赦星")
    Yima = (6, "驿马")
    Taohua = (7, "桃花")
    Wenchang = (8, "文昌")
    Wenchangguiren = (9, "文昌贵人")
    Lushen = (10, "禄神")
    Jiesha = (11, "劫煞")
    Huagai = (12, "华盖")
    Jiangxing = (13, "将星")
    Tianxi = (14, "天喜")
    Tianyi = (15, "天医")
    Tianyixing = (16, "天医星")
    Yangren = (17, "阳刃")
    YangrenAlt = (18, "羊刃")
    Zaisha = (19, "灾煞")
    Mouxing = (20, "谋星")
    Wangshen = (21, "亡神")
    Tianluodiwang = (22, "天罗地网")
    GuchenGuasu = (23, "孤辰寡宿")
    Taijiguiren = (24, "太极贵人")
    Guoyinguiren = (25, "国印")
    Jinyu = (26, "金舆")
    Feiren = (27, "飞刃")
    Xueren = (28, "血刃")
    Liuxia = (29, "流霞")
    Hongyan = (30, "红艳")
    Fuxingguiren = (31, "福星贵人")
    Dexiuguiren = (32, "德秀贵人")
    Tianchuguiren = (33, "天厨贵人")
    Tianguanguiren = (34, "天官贵人")
    Xuetang = (35, "学堂")
    Ciguang = (36, "词馆")
    Guchen = (37, "孤辰")
    Guasu = (38, "寡宿")
    Hongluan = (39, "红鸾")
    Goujiaosha = (40, "勾绞煞")
    Yuanchen = (41, "元辰")
    Sangmen = (42, "丧门")
    Diaoke = (43, "吊客")
    Pima = (44, "披麻")
    Pitou = (45, "披头")
    Liuer = (46, "六厄")
    Kongwang = (47, "空亡")
    Sanqiguiren = (48, "三奇贵人")
    Sifei = (49, "四废")
    Yinchayangcuo = (50, "阴差阳错")
    Kuigang = (51, "魁罡")
    Guluan = (52, "孤鸾")
    Shiedabai = (53, "十恶大败")
    Jinshen = (54, "金神")
    Tianzhuan = (55, "天转")
    Dizhuan = (56, "地转")
    Shiling = (57, "十灵")
    Liuxiu = (58, "六秀")
    Bazhuan = (59, "八专")
    Jiuchou = (60, "九丑")
    Tongzisha = (61, "童子煞")
    Gonglu = (62, "拱禄")
    Jinshenx = (63, "进神")
    Gejiaosha = (64, "隔角煞")
